### ISSUE TITLE
`yarn install` isn't creating a dist folder

### ISSUE THREAD

**Issue by edghar88** [deepal/node-dukpt#18]
After running `yarn install`, the `dist` folder for the project is missing. Since the `package.json` has the `main` pointed at `dist/index.js`, the build fails. I was able to temporarily get around the issue by pointing to `src/index.js`.

**Comment by jleskovar-tyro** [comment]
Noticed this as well - resulted in webpack issues since it couldn't find dist directory :/

**Comment by deepal** [comment]
Related to #21 

Thanks for reporting. This seems like a problem in the few recent versions of the package due to a CI issue. This is now fixed in v4.0.3.
