### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by xyxdaily** [deepal/node-dukpt#21]
![image](https://user-images.githubusercontent.com/50726457/168945881-98b1d16f-8b3a-4bd6-91eb-f0de242cfaa5.png)

**Comment by Alexximn** [comment]
has anyone found a way to resolve this? I ran into this after installing dukpt

**Comment by deepal** [comment]
@xyxdaily @Alexximn Thanks for reporting. This seems like a problem in the few recent versions of the package due to a CI issue. This is now fixed in v4.0.3.
