### ISSUE TITLE
Constructor not taking Keymode, Please update the code

### ISSUE THREAD

**Issue by proBeejay141** [deepal/node-dukpt#5]
function Dukpt(bdk, ksn) {
        _classCallCheck(this, Dukpt);

        this.bdk = bdk;
        this.ksn = ksn;
        this._sessionKey = this._deriveDukptSessionKey();
    }

    _createClass(Dukpt, [{
        key: '_deriveDukptSessionKey',
        value: function _deriveDukptSessionKey() {
            var keyMode = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 'datakey';

**Comment by dpjayasekara** [comment]
Could you describe the issue and its impact in detail?

**Comment by proBeejay141** [comment]
i needed to use pinkey as keymode and keymode is not part of Dukpt
constructor's params, so it alway use the default keymode which is datakey
to generate the session_key

**Comment by dpjayasekara** [comment]
I will have a look at this.

**Comment by proBeejay141** [comment]
Okay good...

**Comment by dpjayasekara** [comment]
This is fixed in v2.1.0

**Comment by beyrul** [comment]
Main path of module is dist/index.js so i think keyMode fix also have to add in dist/lib/dukpt.lib.js

**Comment by dpjayasekara** [comment]
Thanks, @beyrul for pointing it out. Fixed it with some additional refactoring in v3.0.0.
